In [3]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
from datetime import datetime

In [4]:
df = pd.read_csv('data/chapter_06_variance_reduction.csv')
df

,row_index,user_id,page,sale_id,date,load_time
0,3861403,59316c4b82d94b75a78e921cc9cff130,menu,NaN,2022-05-19 8:33:57,0.069743
1,3861438,59316c4b82d94b75a78e921cc9cff130,menu,NaN,2022-05-19 8:51:02,0.062672
2,3861465,1358bd56e02f413f853dd86eeba03434,menu,NaN,2022-05-19 8:59:12,0.064599
3,3861524,1358bd56e02f413f853dd86eeba03434,basket,NaN,2022-05-19 9:15:36,0.079555
4,3861617,0f6c2d8f51394430a5ec47268df54e62,menu,NaN,2022-05-19 9:41:48,0.060811
...,...,...,...,...,...,...
4208,4151480,9616d5a066a84361887fe005ec711ca2,menu,NaN,2022-05-25 21:11:56,0.065642
4209,4151559,9616d5a066a84361887fe005ec711ca2,basket,NaN,2022-05-25 21:13:53,0.083710
4210,4151591,9616d5a066a84361887fe005ec711ca2,basket,NaN,2022-05-25 21:14:50,0.069027
4211,4151654,9616d5a066a84361887fe005ec711ca2,menu,NaN,2022-05-25 21:16:24,0.062703
4212,4151688,9616d5a066a84361887fe005ec711ca2,payment,1439586.0,2022-05-25 21:17:29,0.067472

In [7]:
df2 = df[(df.load_time < 1)]
df2

,row_index,user_id,page,sale_id,date,load_time
0,3861403,59316c4b82d94b75a78e921cc9cff130,menu,NaN,2022-05-19 8:33:57,0.069743
1,3861438,59316c4b82d94b75a78e921cc9cff130,menu,NaN,2022-05-19 8:51:02,0.062672
2,3861465,1358bd56e02f413f853dd86eeba03434,menu,NaN,2022-05-19 8:59:12,0.064599
3,3861524,1358bd56e02f413f853dd86eeba03434,basket,NaN,2022-05-19 9:15:36,0.079555
4,3861617,0f6c2d8f51394430a5ec47268df54e62,menu,NaN,2022-05-19 9:41:48,0.060811
...,...,...,...,...,...,...
4208,4151480,9616d5a066a84361887fe005ec711ca2,menu,NaN,2022-05-25 21:11:56,0.065642
4209,4151559,9616d5a066a84361887fe005ec711ca2,basket,NaN,2022-05-25 21:13:53,0.083710
4210,4151591,9616d5a066a84361887fe005ec711ca2,basket,NaN,2022-05-25 21:14:50,0.069027
4211,4151654,9616d5a066a84361887fe005ec711ca2,menu,NaN,2022-05-25 21:16:24,0.062703
4212,4151688,9616d5a066a84361887fe005ec711ca2,payment,1439586.0,2022-05-25 21:17:29,0.067472